#!/bin/bash

app=`basename "$0"`
command=$1
args="${*:2}"

if [ "$command" == "test" ]; then

	# Run PHP Unit Tests
	# Get actual script path even if symlinked
	path="$(dirname "$(readlink -f "$0")")"
	if [ ! -e "$path/$app" ]; then
		path="$(cd "$(dirname "$0")" && pwd)"
	fi
	system="$( cd $path && cd ../../../ && pwd )/System"
	cd $system

	pwd

	if [ ! -z "$args" ]; then
	    if [ ${args:0:4} == "play" ]; then
	        phpunit $path/Tests/ $args
	    else
	        phpunit $args $path/Tests/
	    fi
	else
	    phpunit $path/Tests/
	fi

elif [ "$command" != "" ]; then

	# Run Artisan Command
	mrcore mreschke:$app:$command $args

else
	echo "Mrcore $app app helper script"
	echo
	echo "Usage:"
	echo "  Unit Tests:"
	echo "    ./$app test"
	echo "    ./$app test play"
	echo "    ./$app test play-custom"
	echo "    ./$app test --filter=SomeTest"
	echo
	echo "  Laravel Artisan Commands"
	echo "    ./$app somecmd args --option=whatever"
	echo
	echo "  Artisan Migrations and Seeds"
	echo "    ./$app db migrate"
	echo "    ./$app db seed"
	echo "    ./$app db rollback"
	echo "    ./$app db refresh"

fi
