#!/bin/bash

app=`basename "$0"`
args=$@

# Get actual script path even if symlinked
path="$(dirname "$(readlink -f "$0")")"
if [ ! -e "$path/$app" ]; then
	path="$(cd "$(dirname "$0")" && pwd)"
fi
system="$( cd $path && cd ../../../ && pwd )/System"

# Run PHP Unit Tests
cd $system
if [ ! -z "$args" ]; then
	phpunit $path/Tests/ $args
else
	phpunit $args $path/Tests/
fi
